import type { DetectedProvider } from './providerDetector.js';

/**
 * Generates the content of `.storybook/preview.ts` with global decorators
 * for all detected providers.
 */
export function generatePreviewContent(providers: DetectedProvider[]): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by sbook-ai — global decorators for detected providers.`);
  lines.push(`// Customize the mock stores and themes to match your project.`);
  lines.push(``);

  lines.push(`import React from 'react';`);
  lines.push(`import type { Preview } from '@storybook/react';`);

  // Collect all import statements (deduplicated)
  const imports = new Set<string>();
  for (const provider of providers) {
    for (const line of provider.importStatement.split('\n')) {
      if (line.trim()) imports.add(line);
    }
  }
  if (imports.size > 0) {
    lines.push(``);
    for (const imp of imports) {
      lines.push(imp);
    }
  }

  lines.push(``);

  // Build the decorator function
  lines.push(`const preview: Preview = {`);
  lines.push(`  decorators: [`);
  lines.push(`    (Story) => (`);

  // Nest providers outside-in
  const indent = '      ';
  const openTags: string[] = [];
  const closeTags: string[] = [];

  for (const provider of providers) {
    const openTag = provider.wrapper.replace('{children}', '');
    // Split opening and closing tag
    const closeMatch = openTag.match(/<\/\w+>/g);
    const closeTag = closeMatch ? closeMatch[closeMatch.length - 1] : '';
    const open = openTag.replace(closeTag, '').trimEnd();

    openTags.push(open);
    closeTags.unshift(closeTag);
  }

  for (const tag of openTags) {
    lines.push(`${indent}${tag}`);
  }
  lines.push(`${indent}  <Story />`);
  for (const tag of closeTags) {
    lines.push(`${indent}${tag}`);
  }

  lines.push(`    ),`);
  lines.push(`  ],`);
  lines.push(`  parameters: {`);
  lines.push(`    controls: {`);
  lines.push(`      matchers: {`);
  lines.push(`        color: /(background|color)$/i,`);
  lines.push(`        date: /Date$/i,`);
  lines.push(`      },`);
  lines.push(`    },`);
  lines.push(`  },`);
  lines.push(`};`);
  lines.push(``);
  lines.push(`export default preview;`);
  lines.push(``);

  return lines.join('\n');
}
