import crypto from 'crypto';
import path from 'path';
import type { ComponentMeta } from '../parser/componentParser.js';
import { mapPropToArgType, getDefaultArg, isComponentRef, type ArgTypeMeta, type ComponentRef } from '../mapper/typeMapper.js';
import { detectVariantProp, generateVariantStories } from '../mapper/variantDetector.js';
import type { AiStoryArgs } from '../ai/argGenerator.js';

export interface BuildStoryOptions {
  /** AI-generated args to use instead of defaults */
  aiArgs?: AiStoryArgs;
}

/**
 * Generates a complete CSF3 .stories.ts file as a string.
 */
export function buildStoryContent(
  meta: ComponentMeta,
  relativePath: string,
  options: BuildStoryOptions = {},
): string {
  const date = new Date().toISOString().split('T')[0];
  const checksum = computeChecksum(meta);

  const importPath = buildImportPath(relativePath);
  const title = buildTitle(meta.filePath);
  const argTypes = buildArgTypes(meta);
  const defaultArgs = options.aiArgs?.Default ?? buildDefaultArgs(meta);

  const variantProp = detectVariantProp(meta.props);
  const variantStories = variantProp ? generateVariantStories(variantProp) : [];

  const lines: string[] = [];

  // Header comment
  lines.push(`// @sbook-ai checksum: ${checksum} generated: ${date}`);
  lines.push(`// AUTO-GENERATED — do not edit this file manually.`);
  lines.push(``);

  // Collect all component refs from args for import generation
  const allArgs = [defaultArgs, ...Object.values(options.aiArgs?.variants ?? {})];
  // Also include fallback variant args if no AI variant args
  if (!options.aiArgs?.variants || Object.keys(options.aiArgs.variants).length === 0) {
    for (const variant of variantStories) {
      const fallbackArgs: Record<string, unknown> = { ...defaultArgs };
      allArgs.push(fallbackArgs);
    }
  }
  const componentRefs = collectComponentRefs(allArgs);

  // Imports
  lines.push(`import type { Meta, StoryObj } from '@storybook/react';`);

  // Component ref imports (grouped by source)
  if (componentRefs.length > 0) {
    const refsBySource = new Map<string, string[]>();
    for (const ref of componentRefs) {
      const existing = refsBySource.get(ref.importSource) ?? [];
      existing.push(ref.importName);
      refsBySource.set(ref.importSource, existing);
    }
    for (const [source, names] of refsBySource) {
      lines.push(`import { ${names.join(', ')} } from '${source}';`);
    }
  }

  lines.push(`import ${meta.name} from '${importPath}';`);
  lines.push(``);

  // Meta object
  lines.push(`const meta: Meta<typeof ${meta.name}> = {`);
  lines.push(`  title: '${title}',`);
  lines.push(`  component: ${meta.name},`);
  lines.push(`  tags: ['autodocs'],`);

  if (argTypes.length > 0) {
    lines.push(`  argTypes: {`);
    for (const at of argTypes) {
      const entry = serializeArgType(at);
      lines.push(`    ${at.name}: { ${entry} },`);
    }
    lines.push(`  },`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`export default meta;`);
  lines.push(`type Story = StoryObj<typeof ${meta.name}>;`);
  lines.push(``);

  // Default story
  lines.push(`export const Default: Story = {`);
  if (Object.keys(defaultArgs).length > 0) {
    lines.push(`  args: {`);
    for (const [k, v] of Object.entries(defaultArgs)) {
      lines.push(`    ${k}: ${serializeArgValue(v)},`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`);

  // Variant stories from detected variant prop
  const emittedVariantNames = new Set<string>();
  for (const variant of variantStories) {
    const variantName = sanitiseIdentifier(variant.name);
    emittedVariantNames.add(variant.name);
    const aiVariantArgs = options.aiArgs?.variants?.[variant.name];

    lines.push(``);
    lines.push(`export const ${variantName}: Story = {`);
    lines.push(`  args: {`);

    if (aiVariantArgs) {
      // Use AI-generated args for this variant
      for (const [k, v] of Object.entries(aiVariantArgs)) {
        lines.push(`    ${k}: ${serializeArgValue(v)},`);
      }
    } else {
      // Fallback: spread default args with variant value
      for (const [k, v] of Object.entries(defaultArgs)) {
        if (k === variantProp!.name) continue;
        lines.push(`    ${k}: ${serializeArgValue(v)},`);
      }
      lines.push(`    ${variantProp!.name}: '${variant.value}',`);
    }

    lines.push(`  },`);
    lines.push(`};`);
  }

  // Emit custom variant args not already covered by detected variant prop
  if (options.aiArgs?.variants) {
    for (const [name, args] of Object.entries(options.aiArgs.variants)) {
      if (emittedVariantNames.has(name)) continue;
      const variantName = sanitiseIdentifier(name);
      lines.push(``);
      lines.push(`export const ${variantName}: Story = {`);
      lines.push(`  args: {`);
      for (const [k, v] of Object.entries(args)) {
        lines.push(`    ${k}: ${serializeArgValue(v)},`);
      }
      lines.push(`  },`);
      lines.push(`};`);
    }
  }

  lines.push(``);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function computeChecksum(meta: ComponentMeta): string {
  const signature = meta.props.map((p) => `${p.name}:${p.typeName}:${p.required}`).join(',');
  return crypto.createHash('sha1').update(signature).digest('hex').slice(0, 12);
}

function buildImportPath(relativePath: string): string {
  // Remove extension for import
  const withoutExt = relativePath.replace(/\.(tsx?|jsx?)$/, '');
  if (!withoutExt.startsWith('.')) return `./${withoutExt}`;
  return withoutExt;
}

function buildTitle(filePath: string): string {
  const parts = filePath.split(path.sep);
  // Find src or components in path to build a sensible title
  const srcIdx = parts.lastIndexOf('src');
  const compIdx = parts.lastIndexOf('components');
  const startIdx = Math.max(srcIdx, compIdx);
  const relevant = startIdx >= 0 ? parts.slice(startIdx + 1) : [parts[parts.length - 1]];
  return relevant
    .map((p) => p.replace(/\.(tsx?|jsx?)$/, ''))
    .join('/');
}

function buildArgTypes(meta: ComponentMeta): ArgTypeMeta[] {
  return meta.props.map(mapPropToArgType);
}

function buildDefaultArgs(meta: ComponentMeta): Record<string, unknown> {
  const args: Record<string, unknown> = {};
  for (const prop of meta.props) {
    const val = getDefaultArg(prop);
    if (val !== undefined) {
      args[prop.name] = val;
    }
  }
  return args;
}

/** Serialize a single argType entry to an inline object string, e.g. `control: 'select', options: ['a','b']` */
function serializeArgType(at: ArgTypeMeta): string {
  const parts: string[] = [];

  if (at.action !== undefined) {
    parts.push(`action: '${at.action}'`);
  } else if (at.control !== undefined) {
    if (at.control === false) {
      parts.push(`control: false`);
    } else if (typeof at.control === 'string') {
      parts.push(`control: '${at.control}'`);
    } else {
      parts.push(`control: { type: '${at.control.type}' }`);
    }
  }

  if (at.options) {
    parts.push(`options: [${at.options.map((o) => `'${o}'`).join(', ')}]`);
  }
  if (at.description) {
    parts.push(`description: ${JSON.stringify(at.description)}`);
  }
  if (at.table?.disable) {
    parts.push(`table: { disable: true }`);
  }

  return parts.join(', ');
}

function sanitiseIdentifier(name: string): string {
  // Replace non-alphanumeric chars and ensure starts with capital
  const clean = name.replace(/[^a-zA-Z0-9]/g, '_');
  return clean.charAt(0).toUpperCase() + clean.slice(1);
}

/** Serialize an arg value — handles ComponentRef markers as raw identifiers. */
function serializeArgValue(value: unknown): string {
  if (isComponentRef(value)) {
    return value.importName;
  }
  return JSON.stringify(value);
}

/** Collect unique ComponentRef values from multiple arg objects. */
function collectComponentRefs(argSets: Record<string, unknown>[]): ComponentRef[] {
  const refs: ComponentRef[] = [];
  const seen = new Set<string>();
  for (const args of argSets) {
    for (const v of Object.values(args)) {
      if (isComponentRef(v)) {
        const key = `${v.importName}:${v.importSource}`;
        if (!seen.has(key)) {
          seen.add(key);
          refs.push(v);
        }
      }
    }
  }
  return refs;
}
